# This is a basic workflow to help you get started with Actions

name: Download file from morph.io

on: repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Download the latest BE file from morph.io
    # BE scraper is currently disabled
    #- name: Download BE CSV from morph.io
    #  env:
    #    morph_key: ${{ secrets.MORPH_KEY }}
    #  run: curl "https://morph.io/metaodi/covid-19-scraper-canton-be/data.csv?key=$morph_key&query=select+%2A+from+%22data%22" --output fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_BE_total.csv  
    
    # Download the latest SG file from morph.io
    # - name: Download SG CSV from morph.io
    #  env:
    #    morph_key: ${{ secrets.MORPH_KEY }}
    #  run: curl "https://morph.io/metaodi/covid-19-scraper-canton-sg/data.csv?key=$morph_key&query=select+%2A+from+%22data%22" --output fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_SG_total.csv  
    
    
    # Download the latest JU file from morph.io
    - name: Download JU CSV from morph.io
      env:
        morph_key: ${{ secrets.MORPH_KEY }}
      run: curl "https://morph.io/metaodi/covid-19-scraper-canton-ju/data.csv?key=$morph_key&query=select+%2A+from+%22data%22" --output fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_JU_total.csv  
    
    #validate CSV
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test
      
    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update covid-19 from morph.io scraper
        branch: ${{ github.head_ref }}
