name: Run AI scraper

on:
  schedule:
    - cron:  '52 * * * *'

jobs:
  run_scraper:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install sqlite3
        
    - name: Scrape new data
      env:
        SCRAPER_KEY: AI
        SCRAPER_SOURCE: https://www.ai.ch/themen/gesundheit-alter-und-soziales/gesundheitsfoerderung-und-praevention/uebertragbare-krankheiten/coronavirus
      run: |
        ./scrapers/run_scraper.sh
        
    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update COVID19_Fallzahlen_Kanton_AI_total.csv from scraper
        branch: ${{ github.head_ref }}
